### ISSUE TITLE
[FEATURE] Add DevOps pipeline to consume existing pytests and run in AzureML 

### ISSUE THREAD

**Issue by bethz** [microsoft/nlp-recipes#134]
### Description
In issue #126 AbhiramE, Casey and others are creating unit tests. This effort will create DevOps pipelines to run the unit tests in AzureML.  The pipelines will be stored in yml files in tests/ci with filenames that correspond to the pipelines.

### Expected behavior with the suggested feature
This function will add confidence that our solutions function as expected.

**Comment by hlums** [comment]
New issue created to track this #538
