### ISSUE TITLE
[BUG] We should have a separate package yaml file for the utils_nlp package

### ISSUE THREAD

**Issue by kehuangms** [microsoft/nlp-recipes#361]
### Description

Right now all dependencies are generated by running "generate_conda_file.py" file to generate the .yaml file, but it would be better if we have separate dependency file for the utils_nlp package. 

When we release utils_nlp as a pip installable package, users are expecting to have all dependencies listed somewhere. On my Windows machine (with GPU), even the pytorch-pretrained-bert and dask packages are listed in the nlp_gpu.yaml file, it's not installed properly. I need to manually install those packages to run the notebook "entailment_multinli_bert".

**Comment by sharatsc** [comment]
Closing due to conda limitations. Wont fix for now
