### ISSUE TITLE
[BUG] I can not pip install the utils module

### ISSUE THREAD

**Issue by georgeAccnt-GH** [microsoft/nlp-recipes#364]
### Description

(nlptest_gpu) loginvm001@ghiordanxray05vm:/datadrive01/prj/nlp$ pip install -e  git+git@github.com:microsoft/nlp.git@master#egg=utils_nlp
Obtaining utils_nlp from git+git@github.com:microsoft/nlp.git@master#egg=utils_nlp
  Cloning git@github.com:microsoft/nlp.git (to revision master) to ./src/utils-nlp
  Running command git clone -q git@github.com:microsoft/nlp.git /datadrive01/prj/nlp/src/utils-nlp
  Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
  Permission denied (publickey).
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
ERROR: Command errored out with exit status 128: git clone -q git@github.com:microsoft/nlp.git /datadrive01/prj/nlp/src/utils-nlp Check the logs for full command output.
(nlptest_gpu) loginvm001@ghiordanxray05vm:/datadrive01/prj/nlp$ git status
On branch ghiordan_test01
Your branch is ahead of 'origin/staging' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean
(nlptest_gpu) loginvm001@ghiordanxray05vm:/datadrive01/prj/nlp$

**Comment by daden-ms** [comment]
@georgeAccnt-GH Can you try to generate ssh keys (skip this if you already have a pair) and upload the public key to your github account by following https://help.github.com/en/articles/adding-a-new-ssh-key-to-your-github-account

**Comment by awaemmanuel** [comment]
@georgeAccnt-GH Did you install your SSH key and get this to work?

**Comment by georgeAccnt-GH** [comment]
Can we do it via a personal access token (PAT) ( "https://github.com/settings/tokens), similar to how it is being done here?
https://github.com/Azure/azureml-sdk-for-r

**Comment by sharatsc** [comment]
Fixed.
