### ISSUE TITLE
[BUG] azureml_utils.py don't create config.json if it doesn't exist in config_path

### ISSUE THREAD

**Issue by hlums** [microsoft/nlp-recipes#366]
### Description

The question_answering_system_bidaf_quickstart.ipynb notebook fails with the following error
---------------------------------------------------------------------------
UserErrorException                        Traceback (most recent call last)
<ipython-input-6-b26cf1b9be00> in <module>
      4     resource_group=resource_group,
      5     workspace_name=workspace_name,
----> 6     workspace_region=workspace_region,
      7 )

/data/home/hlu/notebooks/NLP/utils_nlp/azureml/azureml_utils.py in get_or_create_workspace(config_path, subscription_id, resource_group, workspace_name, workspace_region)
     54         # get existing azure ml workspace
     55         if config_path is not None:
---> 56             ws = Workspace.from_config(config_path, auth=get_auth())
     57         else:
     58             ws = Workspace.get(

/data/anaconda/envs/nlp_gpu/lib/python3.6/site-packages/azureml/core/workspace.py in from_config(path, auth, _logger, _file_name)
    167                 raise UserErrorException('We could not find config.json in: {} or in its parent directories. '
    168                                          'Please provide the full path to the config file or ensure that '
--> 169                                          'config.json exists in the parent directories.'.format(normalized_path))
    170 
    171         subscription_id, resource_group, workspace_name = project_info.get_workspace_info(found_path)

UserErrorException: We could not find config.json in: /data/home/hlu/notebooks/NLP/examples/question_answering/.azureml or in its parent directories. Please provide the full path to the config file or ensure that config.json exists in the parent directories.

Looks like it's a bug in azureml_utils.py

### How do we replicate the bug?

Run the notebook question_answering_system_bidaf_quickstart.ipynb

**Comment by sharatsc** [comment]
Fixed in https://github.com/microsoft/nlp-recipes/pull/367
