### ISSUE TITLE
[ASK] Add Languages to all the scenarios

### ISSUE THREAD

**Issue by sharatsc** [microsoft/nlp-recipes#484]
### Description
Add languages to all scenario tables

**Comment by devjav786** [comment]
can anyone have solution to this Execption


WebserviceException: WebserviceException:
	Message: Image creation polling reached non-successful terminal state, current state: Failed
Error response from server:
StatusCode: 400
Message: Docker image build failed.
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Image creation polling reached non-successful terminal state, current state: Failed\nError response from server:\nStatusCode: 400\nMessage: Docker image build failed."

**Comment by devjav786** [comment]
Anyone on this issue can help ?
