### ISSUE TITLE
[ASK] Do we need to clean the notebooks in text classification scenario?

### ISSUE THREAD

**Issue by kehuangms** [microsoft/nlp-recipes#491]
### Description

Since we are using transformers instead of pre-trained BERT model. Do we need to remove the old notebooks?
- tc_bbc_bert_hi.ipynb
- tc_dac_bert_ar.ipynb
- tc_mnli_xlnet.ipynb

A multi languages notebook is created to integrate all those 3 datasets.

**Comment by saidbleik** [comment]
#486
