### ISSUE TITLE
Comparison of FastText implementations (Facebook vs. Gensim)

### ISSUE THREAD

**Issue by cocochrane** [microsoft/nlp-recipes#56]
@miguelgfierro mentioned that a colleague told him that Facebook's fastText implementation is faster and more accurate than the original one. He thinks its would be worthwhile to do a comparison (time, dataset size, accuracy, etc.) on several datasets. 

References:
https://github.com/RaRe-Technologies/gensim/issues/1940
https://github.com/miguelgfierro/sciblog_support/blob/master/Intro_to_NLP_with_fastText/Intro_to_NLP.ipynb
https://course.fast.ai/datasets#nlp

**Comment by hlums** [comment]
Close stale issue. Feel free to reopen if interested.
