### ISSUE TITLE
[FEATURE] Evaluate PyTorch Text

### ISSUE THREAD

**Issue by eedeleon** [microsoft/nlp-recipes#89]
### Description
Look into depending on PyTorch Text. Document and evaluate :

1. General repo structure
2. Examples related to our current work and what would have to change for adoption
3. Aggregate issues and general direction / pace of contributions

### Expected behavior with the suggested feature

This change should:
1. simplify our Dataset logic to depending on the library and contributing back to it.
2 Allow us to contribute back to the community
3. Keep up to date with NLP idioms being introduced
4. Increase team familiarity and possibly contributions to the PyTorch + NLP ecosystem

**Comment by hlums** [comment]
Close stale issue. Feel free to re-open if interested.
